### ISSUE TITLE
اضافه کردن رنگ ها با فرمت JSON

### ISSUE THREAD

**Issue by mpourismaiel** [IKAcc/RangeBrand#4]
در حال حاضر همه رنگ‌ها تو یه فایل css ذخیره شدن و برای اضافه کردن یه رنگ جدید به یه برند (تغییر از یک رنگ به دو رنگ) علاوه بر تغییر فایل css باید تو فایل html هم تغییر داده بشه.
میشه همه رنگ‌ها رو تو یه فایل با فرمت JSON (یا هر فرمت دیگه) ذخیره کرد و با JS هر برند رو نمایش داد و همه چیز رو داینامیک کرد. ضمن اینکه اینجوری پروژه کاملا میتونه اوپن‌سورس بشه.
ضمن اینکه گیتهاب راست به چپ رو خوب پشتیبانی نمیکنه بهتره متن‌ها انگلیسی باشن.

**Comment by Javid-Izadfar** [comment]
<p dir="rtl">@mpourismaiel این که سایت رو بیشتر داینامیک بکنیم رو توی ذهنمون داشتیم. ممنونیم ازت که JSON رو پیشنهاد دادی. اما مسئله‌ای که هست اینه که فعلا تصمیم نداریم قالب سایت رو هم اوپن سورس بکنیم.</p>

<p dir="rtl">در ضمن، اگه متن فارسی داخل تگ‌های HTML ذخیره بشن، نمایش مناسبی خواهند داشت. الان شما توی صفحه‌هاتی که آماده شدن، مشکلی دارین؟</p>

**Comment by mpourismaiel** [comment]
@Javid-Izadfar نیازی به اوپن سورس کردن تم نیست. میشه JSON رو با یه لایبرری پارس کرد و با فرمتی که نیازه نمایش داد.

**Comment by Javid-Izadfar** [comment]
<p dir="rtl">به زودی یکی از بچه‌ها روی این موضوع کار خواهد کرد </p>

**Comment by mpourismaiel** [comment]
من امشب روش کار میکنم و پول ریکوئست میدم.

**Comment by mpourismaiel** [comment]
Checkout pull request #5

**Comment by mehrnooshdsht** [comment]
درود
از همکاریتون خیلی ممنونم @mpourismaiel .
 من یه سری سوال دارم ازتون میشه لطف کنید و به تلگرام من @Mehrnooshdsht مسیج بدید ممنونم میشم
:)
